//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190442010026.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_diri
    {
        public int id { get; set; }
        public Nullable<System.DateTime> tanggal_daftar { get; set; }
        public string nama_pengemudi { get; set; }
        public string plat_nomor { get; set; }
        public string nomor_sim { get; set; }
        public string keterangan { get; set; }
        public Nullable<decimal> minimal_jam_kerja { get; set; }
        public string foto { get; set; }
    }
}
