//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190442010026.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OjekOnlineEntities : DbContext
    {
        public OjekOnlineEntities()
            : base("name=OjekOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pendapatan> pendapatans { get; set; }
        public virtual DbSet<pengemudi> pengemudis { get; set; }
        public virtual DbSet<view_pendapatan> view_pendapatan { get; set; }
    }
}
