//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190442010026.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_pendapatan
    {
        public int id_pendapatan { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public int id_pengemudi { get; set; }
        public string nama_pengemudi { get; set; }
        public string nomor_sim { get; set; }
        public Nullable<decimal> gaji_perjam { get; set; }
        public Nullable<decimal> insentif_makan { get; set; }
        public Nullable<decimal> insentif_bensin { get; set; }
        public Nullable<decimal> jumlah_jam_perbulan { get; set; }
        public Nullable<decimal> total_pendapatan { get; set; }
        public Nullable<decimal> potongan { get; set; }
    }
}
